"""
    DiGA API

    API zum DiGA-Verzeichnis https://diga.bfarm.de/de/ des Bundesinstituts für Arzneimittel und Medizinprodukte BfArM. Das Verzeichnis bietet eine Auswahl an digitalen Gesundheitsanwendungen (DiGA), die vom BfArM gemäß § 139e SGB V bewertet wurden.   Anfragen sind als GET-requests zu stellen, wobei zur Authorisierung ein Bearer Token im Header \"authorization\" anzugeben ist, der wiederum einem GET-request an https://diga.bfarm.de/de/verzeichnis zu entnehmen ist (Im contetn von meta name=\"host-app/config/environment\" unter \"APP\"/\"fhir\"/\"token\").   # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.diga.api.default_api import DefaultApi  # noqa: E501

from deutschland import diga


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_catalog_entry_get(self):
        """Test case for catalog_entry_get

        CatalogEntry  # noqa: E501
        """
        pass

    def test_charge_item_definition_get(self):
        """Test case for charge_item_definition_get

        ChargeItemDefinition  # noqa: E501
        """
        pass

    def test_device_definition_get(self):
        """Test case for device_definition_get

        DeviceDefinition  # noqa: E501
        """
        pass

    def test_organization_get(self):
        """Test case for organization_get

        Organization  # noqa: E501
        """
        pass

    def test_questionnaire_get(self):
        """Test case for questionnaire_get

        Questionnaire  # noqa: E501
        """
        pass

    def test_questionnaire_response_get(self):
        """Test case for questionnaire_response_get

        Questionnaire  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
