"""
    DiGA API

    API zum DiGA-Verzeichnis https://diga.bfarm.de/de/ des Bundesinstituts für Arzneimittel und Medizinprodukte BfArM. Das Verzeichnis bietet eine Auswahl an digitalen Gesundheitsanwendungen (DiGA), die vom BfArM gemäß § 139e SGB V bewertet wurden.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.diga.model.digalist_included_inner import DigalistIncludedInner

from deutschland import diga


class TestDigalistIncludedInner(unittest.TestCase):
    """DigalistIncludedInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDigalistIncludedInner(self):
        """Test DigalistIncludedInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DigalistIncludedInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
