"""
    DiGA API

    API zum DiGA-Verzeichnis https://diga.bfarm.de/de/ des Bundesinstituts für Arzneimittel und Medizinprodukte BfArM. Das Verzeichnis bietet eine Auswahl an digitalen Gesundheitsanwendungen (DiGA), die vom BfArM gemäß § 139e SGB V bewertet wurden.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.diga.model.digaprescription_meta import DigaprescriptionMeta

from deutschland import diga


class TestDigaprescriptionMeta(unittest.TestCase):
    """DigaprescriptionMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDigaprescriptionMeta(self):
        """Test DigaprescriptionMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DigaprescriptionMeta()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
